version: 1
datastore:
  filename: /app/stats/info.json
scheduler: 
  interval: 10
eventstores:
  station:
    url: http://storage:8090/storage/rapidtransit/status
  maintenance:
    url: http://storage:8090/storage/rapidtransit/maintenance